# Generated by Django 4.0.5 on 2022-07-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
